import { HEADER_NAV_ITEMS, HOME_CAROUSEL_IMAGES } from './Items';
import {
  ABOUT_KOREAN_TEXT,
  CONSULTING_KOREAN_TEXT,
  CONSULTING_KOREAN_TABLE,
  CONSULTING_KOREAN_TABS,
  PARTNERS_KOREAN_TEXTS,
  PORTFOLIO_KOREAN_TEXTS,
} from './Korean';

export {
  ABOUT_KOREAN_TEXT,
  CONSULTING_KOREAN_TEXT,
  CONSULTING_KOREAN_TABLE,
  CONSULTING_KOREAN_TABS,
  PARTNERS_KOREAN_TEXTS,
  PORTFOLIO_KOREAN_TEXTS,
  HEADER_NAV_ITEMS,
  HOME_CAROUSEL_IMAGES,
};
